version: "3"

# Services
services:

  ##
  # Frontend: 'nginx'
  ##
  nginx:
    # On utilise nginx:1.23.1 comme image de base.
    image: nginx:1.23.1

    # On monte le fichier nginx.conf sur /etc/nginx/conf.d/default.conf.
    # Le fichier est monté en read-only sur le container.
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

    # On connecte le container au réseau 'wordpress'
    networks:
      - wordpress
    # On publie le 8000 de l'hote vers le port 8000 du container.
    ports:
      - 127.0.0.1:8000:8000

    # On démarre le service 'nginx' après 'wp'.
    depends_on:
      - wp
    restart: unless-stopped

  ##
  # Backend: 'db'
  ##
  db:
    # On utilise mariadb:10.6.8 comme image de base.
    image: mariadb:10.6.8

    # On définit les variables d'environnement du service 'db' depuis le fichier .env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: yes
    
    # On connecte le container au réseau 'wordpress'.
    networks:
      - wordpress
    # On expose le port 3306 du container.
    expose:
      - 3306

    # On monte le volume Docker 'db' sur /var/lib/mysql.
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  ##
  # Application: 'wp'
  ##
  wp:
    # On utilise wordpress:6.0.1 comme image de base.
    image: wordpress:6.0.1

    # On définit les variables d'environnement du service 'db' depuis le fichier .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    
    # On connecte le container au réseau 'wordpress'
    networks:
      - wordpress
    # On expose le port 80 du container.
    expose:
      - 80

    # On monte le volume Docker 'wp' sur /var/www/html.
    volumes:
      - wp:/var/www/html

    # On démarre le service 'wp' après 'db'.
    depends_on:
      - db
    restart: unless-stopped

# Volumes
volumes:
  # On crée un volume Docker 'db'
  db:
  # On crée un volume Docker 'wp'
  wp:

# Réseaux
networks:
  # On crée un réseau 'wordpress'.
  wordpress:
    name: ${COMPOSE_PROJECT_NAME}
